set mouse=a
set autowrite
set noswapfile
set nowritebackup
set hidden
set number
set ignorecase
set smartcase
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set undofile
set undodir=$HOME/.config/nvim/undo
set undolevels=1000
set undoreload=10000
set backspace=indent,eol,start

set nocompatible
filetype off

set rtp+=~/.ashell/vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'


Plugin 'vim-airline/vim-airline'
Plugin 'scrooloose/nerdtree'

Plugin 'pangloss/vim-javascript'
Plugin 'othree/yajs.vim'
Plugin 'wakatime/vim-wakatime'
Plugin 'adryd/vim-adryd-monokai'
Plugin 'vim-airline/vim-airline-themes'


call vundle#end()
filetype plugin indent on

nnoremap <silent> <leader>ev :e $MYVIMRC<CR>
nnoremap <silent> <leader>pi :PlugInstall<CR>
nnoremap <silent> <leader>pu :PlugUpdate<CR>
nnoremap <silent> <leader>pg :PlugUpgrade<CR>
nnoremap <silent> <leader>sv :source $MYVIMRC<CR>

nnoremap <silent> <C-L> :noh<CR>
nnoremap <silent> <A-[> :bp<CR>
nnoremap <silent> <A-]> :bn<CR>
" macos's default keyboard layout's option key outputs special characters
" when the option key is held, and macos's alt key is option -- account for
" that here
nnoremap <silent> ‘ :bn<CR>
nnoremap <silent> “ :bp<CR>
cnoreabbrev W w
cnoreabbrev Wq wq
cnoreabbrev Qa qa


" truecolor in tmux
let &t_8f="\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b="\<Esc>[48;2;%lu;%lu;%lum"

let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

set termguicolors
set background=dark
let g:gruvbox_italic=1

let g:airline_theme='base16color'
syntax on
colorscheme one
