export PATH="$HOME/bin:/usr/local/bin:/usr/local/opt/bc/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH" # Basic PATH shit
export ADRYDDOTFILES="$HOME/.ashell"
export ZSH="$HOME/.ashell/zsh/oh-my-zsh" # oh my zsh wants this
export NVM_DIR="$HOME/.nvm"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
#export JAVA_HOME=`/usr/libexec/java_home`
JAVA_HOME='/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home'
# GraalVM
export GRAALVM_HOME=~/.path/GraalVM/Contents/Home
# fucks with node 
#export PATH=$GRAALVM_HOME/bin:$PATH

plugins=(
  git
)

# Slows down load time
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" 

HISTSIZE=10000
SAVEHIST=10000
[[ $TMUX ]] && export ISTMUX="1"
EDITOR='vim'

source "${ADRYDDOTFILES}/zsh/oh-my-zsh/oh-my-zsh.sh"

source "${ADRYDDOTFILES}/theme_settings_default.zsh"
source "${ADRYDDOTFILES}/theme_settings.zsh"

source "${ADRYDDOTFILES}/zsh/aliases.zsh"
source "${ADRYDDOTFILES}/misc/private/keys.zsh"
source "${ADRYDDOTFILES}/zsh/personal.zsh"

source "${ADRYDDOTFILES}/themes.zsh"
source "${ADRYDDOTFILES}/zsh/fuckery.zsh"

source "${ADRYDDOTFILES}/zsh/iterm2_shell_integration.zsh"

alias rl='reset && source ~/.zshrc'
alias sync='source ~/.ashell/theme_settings.zsh && resettheme'
alias motd="phant"

resettheme

segments="${ADRYDDOTFILES}/tmux/segments.zsh"
motd
